### PR TITLE
Gunicorn support

### PR DESCRIPTION
**Pull request by akumar-cs**
added cli support for startCertifaiModelServer

default with no-args works as 3 async workers with 30 sec timeout and warn log-level

### CODE REVIEW

**Comment by cdraper-CS** [comment]
Sadly given it doesnt work on Windows, we'll either have to default to the flask implementation and make the gunicorn one an option, OR default to flask for Windows and gunicorn on Linux/Mac.

**Comment by laguirre-cs** [comment]
There seems to be some missing clean-up when using the model server for the scanner unit tests. Even after the unit tests finish, the gunicorn main + worker process keep running.

**Comment by akumar-cs** [comment]
@laguirre-cs https://github.com/CognitiveScale/certifai/pull/2594 fix here. last commit

**Comment by akumar-cs** [comment]
@laguirre-cs @cdraper-CS  added support for defaulting to vanilla flask for windows

**Pull request merged**
